<?php
$this->headTitle('Add expense');
/** @var \Domain\Query\ReadEvent\ReadEventDTO $event */
?>

<div class="row">
    <div class="offset-lg-3 col-lg-6 offset-md-2 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="form-group">
                        <label for="description">Description</label>
                        <input name="description" type="text" class="form-control" id="description">
                    </div>
                    <div class="form-group">
                        <label for="amount">Amount</label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">&euro;</div>
                            </div>
                            <input name="amount" type="text" class="form-control" id="amount">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="paidBy">Paid by</label>
                        <select name="paidBy" class="form-control" id="paidBy">
                            <?php foreach($event->getMembers() as $member): ?>
                                <option><?=$member?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>
    </div>
</div>
