<?php $this->headTitle('Create event'); ?>

<div class="row">
    <div class="offset-lg-3 col-lg-6 offset-md-2 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="form-group">
                        <label for="event-name">Event name</label>
                        <input name="eventName" type="text" class="form-control" id="event-name">
                    </div>
                    <div class="form-group">
                        <label for="members">Members</label>
                        <input name="members" type="text" class="form-control" id="members">
                        <small id="passwordHelpBlock" class="form-text text-muted">
                            Укажите имена, разделяя запятой.
                        </small>
                    </div>

                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>
