<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">zend-expressive</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/zend-expressive-skeleton" target="_blank">zend-expressive skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        Expressive builds on zend-stratigility to provide a minimalist PSR-7 middleware framework for PHP.
    </p>
</div>

<div class="row">
    <div class="offset-4 col-md-4">
        <a class="btn btn-primary btn-lg btn-block" href="<?=$this->url('create-event')?>" role="button">
            Create event&nbsp;&nbsp;<i class="fa fa-hand-point-right"></i>
        </a>
    </div>
</div>
